# Generated by Django 5.0.6 on 2024-05-19 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('guest_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('url', models.ImageField(upload_to='cocktails')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('url', models.ImageField(upload_to='dessert')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.ImageField(upload_to='menu')),
            ],
        ),
        migrations.RenameModel(
            old_name='DrinksCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='description',
        ),
        migrations.AddField(
            model_name='drinks',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AddField(
            model_name='drinks',
            name='url',
            field=models.ImageField(default='Default Title', upload_to='drinks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
