# Generated by Django 5.0.6 on 2024-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_cocktail_dessert_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
