# Generated by Django 5.0.6 on 2024-05-17 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_drink_drinks_title_alter_drinks_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinksCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='Category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.category'),
        ),
    ]
